### ISSUE TITLE
Impossible to attack King of Dwarves during 3rd stage when 1-hitting him during 1st stage

### ISSUE THREAD

**Issue by Brongil** [Zrp200/rkpd2#3]
Hey, just ran into a Bug(?), where i was not able to attack the King of Dwarves during the 3rd stage in version 0.3.1. I 1-hit him after 9 rounds of staying cloaked, directly into the 2nd stage, which worked as normal. But in the 3rd stage the King had 0 hp and was unhitable/assassinatable/invulnerable to gas of corrosion and icewand but still ran around spawning minions. Might be a bug?

Thank you
Brongil

(Mabe) Relevant build Info: Assassin, Sucker Punch +2, Enhanced Lethality +3, Enhanced Rings +3, 18 str, Glaive +12, ring of force +3, Cloak of Shadows

[EDIT] I should add that it happened on Android 11. If any further information is required I'll add it off course.
If its an issue related to shattered, I hope you can forward it. 

Thank you

**Comment by Zrp200** [comment]
So, to be clear, you started with him at full HP, had him go through his full phase 2, but he had 0 instead of 50 HP in the last stage and remained invulnerable?

**Comment by halrhyrr** [comment]
Encountered the same issue just now. Was pretty funny actually, it's my first time reaching DK and I didn't realise he wasn't supposed to be spawning that many minions lol.
![Screenshot_20220309-205834](https://user-images.githubusercontent.com/101255609/157423353-7280c388-5e7f-4151-af62-4b3da093de6c.png)

**Comment by Zrp200** [comment]
> Sorry, for not answering your questions for so long. The past few days we're pretty stressful.
> 
> > So, to be clear, you started with him at full HP, hit him really hard, had him go through his full phase 2, but he had 0 instead of 50 HP in the last stage and remained invulnerable?
> 
> Exactly. He had still some HP left when entering phase 2. But the HP-losses from fighting against his minions during the 2nd stage brought him down to 0. He entered stage 3 with 0 HP and was invulnerable
> 
> Thank you very much for all your work

Oh, I see. That's really helpful in finding the bug. I'll see if I can reproduce it when I get a chance. The next opportunity I'll get to patch RKPD2 will probably be late this month, but I'll make sure that this fix is in it.

**Comment by Zrp200** [comment]
I have fixed this indev (as of a week ago :S). It'll be in the next release of RKPD2, which will be soon.
