### ISSUE TITLE
Missing code for 2.0.0

### ISSUE THREAD

**Issue by fgaz** [Zrp200/rkpd2#9]
I noticed the new 2.0.0 release and tried to get the source code, but the 2.0.0 tag points to the same commit as 1.0.0. Could you push the 2.0.0 code and update the tag?

Relatedly, in the 2.0.0 description you write:

> expect a ton of minor updates with the same version number

When releasing minor updates, it would be best if you created new tags such as 2.0.1, 2.0.2... instead of overwriting 2.0.0, since tags are supposed to be immutable.

**Comment by Zrp200** [comment]
Fixed, and the latest release now uses a different tag.

**Comment by fgaz** [comment]
Thanks!
